"""Shared pytest plumbing for the end-to-end suites under ``tests/e2e/``.

Command-line options
--------------------
``--model DIR`` (env fallback ``REDLINE_TEST_MODEL``)
    Path to the Qwen2.5-1.5B-Instruct checkpoint directory the engine loads.
    When absent, engine-backed tests skip cleanly (so a bare ``pytest`` run in
    CI, with no GPU or checkpoint, stays green).
``--ref FILE`` (env fallback ``REDLINE_HF_REF``, honored by the suites)
    Path to a reference JSON produced by ``gen_reference.py`` (suite c) or the
    per-suite fixture generators. When absent, tests that require it skip.
``--engine-kwargs "k=v,k=v"`` (env fallback ``REDLINE_ENGINE_KWARGS``)
    Optional comma-separated overrides merged over the dev-preset defaults when
    constructing ``redline.Engine`` (e.g. the bench preset:
    ``"kv_pool_gb=8,max_batch=64,max_seq_len=4096,prefill_chunk=2048"``). Known
    section-10 keys are type-coerced through the single shared table in
    ``tests/e2e/engine_options.py`` (also used by the suite-(d)/(e) overlays,
    so one spelling parses identically everywhere; ``pad_eager_to_bucket`` is
    integer-valued per src/core/engine.hpp - e.g. ``pad_eager_to_bucket=8`` -
    with ``true``/``false`` accepted as 1/0). Unknown keys pass through
    verbatim and surface as a loud ``TypeError`` from the pybind constructor
    rather than being silently dropped.

Fixtures
--------
``model_dir``      -> str        (session; skips if ``--model`` absent)
``engine_kwargs``  -> dict       (session; parsed ``--engine-kwargs``)
``make_engine``    -> callable   (function; ``make_engine(**overrides)`` builds
                                  a ``redline.Engine``; skips if the module is
                                  not importable - e.g. not yet built)
``report_sink``    -> list[str]  (function; append informational, non-gating
                                  report lines; printed in the terminal summary
                                  so they are visible even under ``pytest -v``)

The e2e tests deliberately do NOT import torch/transformers: reference data is
generated by a separate process (``gen_reference.py``) and consumed here as
JSON, so the engine and HF never share one interpreter or one 6 GiB card.
"""

from __future__ import annotations

import os
import sys

import pytest

# Make sibling modules (prompts.py, engine_options.py, gen_reference.py
# helpers) importable no matter what cwd pytest is invoked from.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from engine_options import get_option, parse_engine_kwargs  # noqa: E402


# --------------------------------------------------------------------------
# CLI options
# --------------------------------------------------------------------------
def pytest_addoption(parser: pytest.Parser) -> None:
    group = parser.getgroup("redline-e2e")
    group.addoption(
        "--model",
        action="store",
        default=None,
        help="Path to the Qwen2.5-1.5B-Instruct checkpoint directory.",
    )
    group.addoption(
        "--ref",
        action="store",
        default=None,
        help="Path to a reference JSON produced by gen_reference.py.",
    )
    group.addoption(
        "--engine-kwargs",
        action="store",
        default=None,
        help="Comma-separated redline.Engine ctor overrides, e.g. "
        "'kv_pool_gb=8,max_batch=64,max_seq_len=4096,prefill_chunk=2048'.",
    )


# --------------------------------------------------------------------------
# Fixtures (--engine-kwargs parsing lives in tests/e2e/engine_options.py -
# one coercion table shared with the suite-(d)/(e) overlays)
# --------------------------------------------------------------------------
@pytest.fixture(scope="session")
def model_dir(pytestconfig: pytest.Config) -> str:
    path = get_option(pytestconfig, "--model", "REDLINE_TEST_MODEL")
    if not path:
        pytest.skip(
            "--model not provided and REDLINE_TEST_MODEL unset "
            "(engine-backed e2e test)"
        )
    if not os.path.isdir(path):
        raise pytest.UsageError(f"--model path is not a directory: {path}")
    return str(path)


@pytest.fixture(scope="session")
def engine_kwargs(pytestconfig: pytest.Config) -> dict[str, object]:
    spec = get_option(pytestconfig, "--engine-kwargs", "REDLINE_ENGINE_KWARGS")
    try:
        return parse_engine_kwargs(spec)
    except ValueError as error:
        raise pytest.UsageError(str(error)) from error


@pytest.fixture
def make_engine(model_dir: str, engine_kwargs: dict[str, object]):
    """Factory building a ``redline.Engine`` from ``model_dir`` + merged kwargs.

    ``make_engine(**overrides)`` merges ``overrides`` over ``--engine-kwargs``
    over the ctor defaults. Skips the test if the ``redline`` extension is not
    importable (e.g. the module has not been built yet), matching the
    skip-cleanly-without-a-device convention of the gtest suites.
    """
    redline = pytest.importorskip(
        "redline", reason="redline extension not built (set PYTHONPATH=$BUILD)"
    )

    def _make(**overrides: object):
        cfg = {**engine_kwargs, **overrides}
        return redline.Engine(model_dir, **cfg)

    return _make


# --------------------------------------------------------------------------
# Informational (non-gating) report sink, surfaced in the terminal summary
# --------------------------------------------------------------------------
_REPORTS_KEY = pytest.StashKey[list]()


def pytest_configure(config: pytest.Config) -> None:
    config.stash[_REPORTS_KEY] = []


@pytest.fixture
def report_sink(request: pytest.FixtureRequest) -> list:
    """A list of report strings printed verbatim in the terminal summary.

    Non-gating suites (e.g. free-running prefix match) append human-readable
    lines here; ``pytest_terminal_summary`` prints them at the end of the run
    regardless of capture settings, so the report is visible under plain
    ``pytest -v`` without ``-s``.
    """
    return request.config.stash.setdefault(_REPORTS_KEY, [])


def pytest_terminal_summary(terminalreporter, exitstatus, config) -> None:  # noqa: ARG001
    reports = config.stash.get(_REPORTS_KEY, [])
    if not reports:
        return
    terminalreporter.write_sep("=", "redline e2e reports (informational)")
    for block in reports:
        for line in str(block).splitlines():
            terminalreporter.write_line(line)
