"""Render benchmark result JSON files into a markdown table.

Input: one JSON file per engine/case as written by bench/run_bench.py
(median-of-trials metrics, min-max spread, raw trials, environment capture;
schema in that module's docstring). Output: one markdown table per case -
engines as rows; output token throughput (labeled as including prefill),
per-request decode rate, TTFT p50/p99, ITL p50/p99 as columns - each cell as
median with min-max, dispersion-flagged where the spread rule fired
(bench/FAIRNESS.md "Trials, dispersion, reporting"). The two vLLM baseline
arms (engines ``vllm`` and ``vllm024``) render as separate rows labeled by
each file's own recorded version ("vllm 0.9.2" / "vllm 0.24.0", from
``engine_config.vllm_version``), and the environment footnote lists both
arms' pins when both are present.

The table caption carries the scope statement (Qwen2.5-1.5B FP16, these
workloads only; no general-superiority claim) and the environment footnote
(GPU, driver, engine versions, measurement date - the date comes from the
results' own environment timestamps). A reproduction section follows: the
harness prerequisites plus the exact recorded command line of every rendered
run, verbatim from its results file's ``environment.command_line``. Every
number is read from a validated results file - this module refuses malformed
files, results without environment capture or forced-length confirmation,
results whose numbers do not recompute from their own committed per-token
data, and result sets measured on differing GPUs. Nothing is ever typed in by
hand.

Usage::

    python -m bench.report --results bench/results/raw/ [--out table.md]
    python -m bench.report --results bench/results/raw/ --write-readme README.md
    python -m bench.report --check bench/results/raw/

``--write-readme`` replaces the block between the markers

    <!-- BENCH_RESULTS:BEGIN (generated by bench/report.py) -->
    <!-- BENCH_RESULTS:END -->

and errors if the markers are missing. ``--check`` audits a directory of raw
results and exits non-zero on any violation, so a directory that passes
``--check`` is guaranteed to render. The audit does not trust a file's own
say-so: beyond the schema gate (duplicate engine/case pairs - the two vLLM
arms are distinct engines, so (vllm, case) and (vllm024, case) coexist -
ambiguous row labels, dispersion flags, environment consistency), it
re-derives the numbers from the committed per-token data - forced output
lengths from the token arrays themselves (``forced_length_ok`` is a claim;
the raw data is the evidence), every per-trial metric via the same
``bench.run_bench.compute_metrics`` that wrote the file, and the summary /
median-trial / dispersion blocks from the per-trial metrics - so truncating
a token list, editing a median, or dropping the raw data fails the check
even when every self-reported flag stays green.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

from bench.adapters import RequestTrace
from bench.run_bench import (
    HEADLINE_METRIC,
    RESULTS_SCHEMA_VERSION,
    compute_metrics,
    select_median_trial,
    spread_exceeds,
    summarize_metrics,
)

README_BEGIN = "<!-- BENCH_RESULTS:BEGIN (generated by bench/report.py) -->"
README_END = "<!-- BENCH_RESULTS:END -->"

CASE_ORDER = ("primary", "arrival", "longout", "batch1")
ENGINE_ORDER = ("redline", "vllm", "vllm024", "llamacpp")

# Columns: (results key, header). The headline column label states that the
# window includes prefill - bench/FAIRNESS.md "Metrics".
COLUMNS = (
    ("throughput_tok_s", "output tok/s (full window, incl. prefill)"),
    ("decode_rate_p50_tok_s", "decode rate p50 (tok/s per request)"),
    ("ttft_p50_s", "TTFT p50 (ms)"),
    ("ttft_p99_s", "TTFT p99 (ms)"),
    ("itl_p50_s", "ITL p50 (ms)"),
    ("itl_p99_s", "ITL p99 (ms)"),
)
_MS_METRICS = {"ttft_p50_s", "ttft_p99_s", "itl_p50_s", "itl_p99_s"}

SCOPE_CAPTION = (
    "Scope: Qwen2.5-1.5B-Instruct, FP16, single GPU, greedy decoding, the "
    "fixed workloads of bench/FAIRNESS.md only. A 1.5B model at high batch is "
    "the regime where host-side per-step overhead matters most; no claim of "
    "general engine superiority is made or implied. Each cell is the median "
    "measured trial with min-max across trials in parentheses (3 trials per "
    "engine/case after one unmeasured warmup, plus one re-run where the "
    "dispersion rule fired; over a re-run's even trial count the reported "
    "median is the lower-middle measured trial, never an interpolated "
    "midpoint - bench/FAIRNESS.md \"Trials, dispersion, reporting\"); † marks "
    "numbers whose min-max spread across all measured trials, the re-run "
    "included, still exceeded 3% of the median. "
    "llamacpp rows are llama-server HTTP serving-path numbers (measured-path "
    "decomposition in bench/FAIRNESS.md). ITL percentiles are pooled across "
    "requests: on the closed-wave cases redline's rare per-request "
    "first-to-second-token prefill stalls lie beyond the pooled p99 cut and "
    "do not appear in the ITL columns - magnitudes are quantified in "
    "bench/FAIRNESS.md \"Metrics\"; read redline's ITL p99 together with "
    "TTFT p99, not as a general tail-latency claim."
)


class ReportError(ValueError):
    """A results file failed validation, or the set is inconsistent."""


# --------------------------------------------------------------------------
# Loading + validation
# --------------------------------------------------------------------------


def _iter_result_files(paths: list[str]) -> list[Path]:
    files: list[Path] = []
    for raw in paths:
        path = Path(raw)
        if path.is_dir():
            files.extend(sorted(path.rglob("*.json")))
        elif path.is_file():
            files.append(path)
        else:
            raise ReportError(f"no such results file or directory: {path}")
    if not files:
        raise ReportError(f"no result JSON files found under {paths}")
    return files


# Tolerance for recomputing per-trial metrics from the committed per-token
# data: run_bench computes metrics from unrounded monotonic timestamps but
# commits the per-request record rebased and rounded to 7 decimal places
# (bench/run_bench._trace_to_json), so a faithful recomputation lands within
# ~1e-7 s per timestamp - worst observed relative shift is ~2.5e-5 on the
# ms-scale ITL percentiles. The bounds below sit ~20x above that floor and
# far below anything a result-altering edit produces.
_RECOMPUTE_REL_TOL = 5e-4
_RECOMPUTE_ABS_TOL = 1e-7


def validate_result(result: dict, source: str = "<memory>") -> None:
    """Validation gate: only numbers measured and written by run_bench.py may
    render. Structural checks first, then the raw-data audit
    (``_audit_raw_data``) that recomputes the file's numbers from its own
    committed per-token data. Raises ReportError naming the file and the
    problem."""

    def fail(problem: str) -> None:
        raise ReportError(f"{source}: {problem}")

    if not isinstance(result, dict):
        fail("not a results object")
    if result.get("schema_version") != RESULTS_SCHEMA_VERSION:
        fail(
            f"schema_version {result.get('schema_version')!r} != "
            f"{RESULTS_SCHEMA_VERSION} (regenerate with bench/run_bench.py)"
        )
    for key in ("engine", "case", "workload", "engine_config", "trials", "dispersion"):
        if key not in result:
            fail(f"missing key {key!r}")
    if result.get("forced_length_ok") is not True:
        fail("forced_length_ok is not true; the trial set is void (FAIRNESS.md)")
    environment = result.get("environment")
    if not isinstance(environment, dict) or "nvidia_smi_q" not in environment:
        fail("environment capture missing (FAIRNESS.md 'Hardware and environment')")
    if "command_line" not in environment:
        fail("environment capture lacks the exact command line")
    if not result["trials"]:
        fail("no measured trials")
    metrics = result.get("metrics")
    if not isinstance(metrics, dict) or HEADLINE_METRIC not in metrics:
        fail(f"summary metrics missing {HEADLINE_METRIC!r}")
    for name, entry in metrics.items():
        for field in ("value", "min", "max", "label"):
            if field not in entry:
                fail(f"metric {name!r} missing {field!r}")
    if "prefill" not in metrics[HEADLINE_METRIC]["label"]:
        fail("headline throughput label must state that the window includes prefill")
    median_index = result.get("median_trial_index")
    if not isinstance(median_index, int) or not 0 <= median_index < len(result["trials"]):
        fail(f"median_trial_index {median_index!r} out of range")
    _audit_raw_data(result, fail)


def _audit_raw_data(result: dict, fail) -> None:
    """The tamper audit behind ``--check`` (and every render): re-derive the
    file's numbers from its own committed per-token data instead of trusting
    the self-reported flags.

    Per trial: forced output lengths straight from the token arrays
    (``forced_length_ok`` alone proves nothing - a truncated ``token_ids``
    next to a green flag must fail), token/timestamp parallelism and
    monotonicity, and every metric recomputed through the same
    ``bench.run_bench.compute_metrics`` that wrote the file (tolerance covers
    only the committed 1e-7 timestamp rounding). Across trials: the summary
    ``metrics`` block must re-derive exactly via ``summarize_metrics`` (value
    = median trial, min/max across trials), ``dispersion.values`` must be the
    trials' headline values, ``median_trial_index`` must be the median by the
    headline metric, and the ``flag``/``reran`` markers must reproduce from
    the spread rule and the trials' own re-run markers."""
    workload = result["workload"]
    for key in ("num_requests", "output_len"):
        if not isinstance(workload.get(key), int) or workload[key] <= 0:
            fail(f"workload.{key} missing or not a positive integer")
    trials = result["trials"]
    for index, trial in enumerate(trials):
        if not isinstance(trial, dict):
            fail(f"trial {index} is not an object")
        requests = trial.get("requests")
        if not isinstance(requests, list) or not requests:
            fail(
                f"trial {index} carries no raw per-request data "
                "(FAIRNESS.md commits per-token JSON for every trial)"
            )
        if len(requests) != workload["num_requests"]:
            fail(
                f"trial {index} has {len(requests)} request records; the "
                f"workload ran {workload['num_requests']}"
            )
        traces = []
        seen_ids = set()
        for request in requests:
            rid = request.get("request_id")
            token_ids = request.get("token_ids")
            token_times = request.get("token_times_s")
            if not isinstance(token_ids, list) or not isinstance(token_times, list):
                fail(f"trial {index} request {rid!r}: token_ids/token_times_s missing")
            if rid in seen_ids:
                fail(f"trial {index}: duplicate request_id {rid!r}")
            seen_ids.add(rid)
            if len(token_ids) != len(token_times):
                fail(
                    f"trial {index} request {rid!r}: {len(token_ids)} token_ids vs "
                    f"{len(token_times)} token_times_s (index-parallel by contract)"
                )
            if len(token_ids) != workload["output_len"]:
                fail(
                    f"trial {index} request {rid!r}: raw record carries "
                    f"{len(token_ids)} tokens, forced output length is "
                    f"{workload['output_len']} - forced_length_ok is contradicted "
                    "by the committed per-token data"
                )
            if any(b < a for a, b in zip(token_times, token_times[1:])):
                fail(f"trial {index} request {rid!r}: token_times_s not non-decreasing")
            traces.append(
                RequestTrace(
                    request_id=rid,
                    enqueue_time=request.get("enqueue_time_s", 0.0),
                    token_times=[float(t) for t in token_times],
                    token_ids=list(token_ids),
                )
            )
        try:
            recomputed = compute_metrics(traces)
        except (TypeError, ValueError) as error:
            fail(f"trial {index}: metrics cannot be recomputed from the raw data ({error})")
        stored = trial.get("metrics")
        if not isinstance(stored, dict) or set(stored) != set(recomputed):
            fail(
                f"trial {index}: stored metric keys "
                f"{sorted(stored) if isinstance(stored, dict) else stored!r} != "
                f"recomputed {sorted(recomputed)}"
            )
        for name, expected in recomputed.items():
            got = stored[name]
            if isinstance(expected, int):
                matches = got == expected
            else:
                matches = isinstance(got, (int, float)) and math.isclose(
                    got, expected, rel_tol=_RECOMPUTE_REL_TOL, abs_tol=_RECOMPUTE_ABS_TOL
                )
            if not matches:
                fail(
                    f"trial {index} metric {name!r}: stored {got!r} != {expected!r} "
                    "recomputed from the committed per-token data"
                )
    if result["metrics"] != summarize_metrics(trials, result["median_trial_index"]):
        fail(
            "summary metrics do not re-derive from the per-trial metrics "
            "(value = median trial, min/max across all trials, FAIRNESS.md labels)"
        )
    dispersion = result["dispersion"]
    headline_values = [t["metrics"][HEADLINE_METRIC] for t in trials]
    if dispersion.get("metric") != HEADLINE_METRIC:
        fail(f"dispersion.metric {dispersion.get('metric')!r} != {HEADLINE_METRIC!r}")
    threshold = dispersion.get("threshold_fraction")
    if not isinstance(threshold, (int, float)) or threshold <= 0:
        fail(f"dispersion.threshold_fraction {threshold!r} is not a positive number")
    if dispersion.get("values") != headline_values:
        fail("dispersion.values do not equal the trials' headline metric values")
    if result["median_trial_index"] != select_median_trial(headline_values):
        fail(
            f"median_trial_index {result['median_trial_index']} is not the median "
            f"trial by {HEADLINE_METRIC} (expected "
            f"{select_median_trial(headline_values)})"
        )
    if bool(dispersion.get("flag")) != spread_exceeds(headline_values, threshold):
        fail("dispersion.flag contradicts the spread rule recomputed over the trials")
    if bool(dispersion.get("reran")) != any(bool(t.get("dispersion_rerun")) for t in trials):
        fail("dispersion.reran contradicts the trials' dispersion_rerun markers")


def load_results(paths: list[str]) -> list[dict]:
    """Load and validate result JSON files; each result gains a ``_source``
    key naming the file it came from."""
    results = []
    for path in _iter_result_files(paths):
        try:
            result = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ReportError(f"{path}: unreadable results JSON ({error})") from error
        validate_result(result, str(path))
        result["_source"] = str(path)
        results.append(result)
    return results


# --------------------------------------------------------------------------
# Environment consistency + footnote
# --------------------------------------------------------------------------


def parse_gpu_name(nvidia_smi_q: str) -> str | None:
    """GPU product name from `nvidia-smi -q` text.

    >>> parse_gpu_name("...\\n    Product Name                          : NVIDIA GeForce RTX 4090\\n...")
    'NVIDIA GeForce RTX 4090'
    >>> parse_gpu_name("no gpu here") is None
    True
    """
    match = re.search(r"^\s*Product Name\s*:\s*(.+?)\s*$", nvidia_smi_q, re.MULTILINE)
    return match.group(1) if match else None


def parse_driver_version(nvidia_smi_q: str) -> str | None:
    """
    >>> parse_driver_version("  Driver Version                        : 560.35.03 ")
    '560.35.03'
    """
    match = re.search(r"^\s*Driver Version\s*:\s*(.+?)\s*$", nvidia_smi_q, re.MULTILINE)
    return match.group(1) if match else None


def _environment_gpu(result: dict) -> tuple[str | None, str | None]:
    capture = result["environment"].get("nvidia_smi_q") or {}
    text = capture.get("output") if isinstance(capture, dict) else None
    if not text:
        return (None, None)
    return (parse_gpu_name(text), parse_driver_version(text))


def check_same_environment(results: list[dict]) -> tuple[str | None, str | None]:
    """All published rows must come from the same GPU model (FAIRNESS.md);
    distinct GPU models are refused outright. Also refuses sets where some
    files carry a parsable GPU capture and others do not: a result whose
    `nvidia-smi -q` capture failed is an environment wildcard, and rendering
    it next to captured results would fake a same-GPU guarantee.

    Results sharing the GPU model but measured under different driver
    versions are the disclosed cross-session two-arm case (the ``vllm024``
    arm is measured in its own pod session on the same GPU model -
    bench/FAIRNESS.md "Engine configuration" pin disclosure): the set
    renders, and the returned driver note names every driver together with
    the rows measured under it, so the footnote never fakes a single-driver
    guarantee. Returns the common (gpu, driver-note); (None, None) only when
    NO file in the set has a capture (the footnote then says so)."""
    by_gpu: dict[str, dict[str | None, list[dict]]] = {}
    missing: list[str] = []
    for result in results:
        gpu, driver = _environment_gpu(result)
        if gpu is None:
            missing.append(result["_source"])
        else:
            by_gpu.setdefault(gpu, {}).setdefault(driver, []).append(result)
    if len(by_gpu) > 1:
        detail = "; ".join(
            f"{gpu} / driver {driver}: "
            f"{', '.join(r['_source'] for r in group)}"
            for gpu, drivers in sorted(by_gpu.items())
            for driver, group in sorted(drivers.items(), key=lambda kv: str(kv[0]))
        )
        raise ReportError(f"results measured under mismatched environments - {detail}")
    if by_gpu and missing:
        raise ReportError(
            "same-environment verification impossible - these results lack a "
            f"parsable `nvidia-smi -q` GPU capture: {', '.join(missing)} "
            "(other files in the set have one; all or none must, "
            "FAIRNESS.md 'Hardware and environment')"
        )
    if not by_gpu:
        return (None, None)
    gpu, drivers = next(iter(by_gpu.items()))
    if len(drivers) == 1:
        return (gpu, next(iter(drivers)))

    def _group_order(item: tuple) -> tuple:
        _, group = item
        return min(_sort_key(ENGINE_ORDER, r["engine"]) for r in group)

    parts = []
    for driver, group in sorted(drivers.items(), key=_group_order):
        labels = []
        for r in sorted(group, key=lambda r: _sort_key(ENGINE_ORDER, r["engine"])):
            label = engine_row_label(r)
            if label not in labels:
                labels.append(label)
        parts.append(f"{driver or 'unrecorded'} ({', '.join(labels)} rows)")
    return (
        gpu,
        " / ".join(parts)
        + " - separate same-GPU-model sessions, disclosed in bench/FAIRNESS.md"
        ' "Engine configuration"',
    )


def _engine_versions(results: list[dict]) -> list[str]:
    pins = []
    for result in results:
        config = result.get("engine_config", {})
        bits = [result["engine"]]
        for key in ("vllm_version", "module_version", "build_info", "version"):
            if config.get(key):
                bits.append(str(config[key]))
        pin = " ".join(bits)
        if pin not in pins:
            pins.append(pin)
    return pins


def _measurement_dates(results: list[dict]) -> list[str]:
    """Sorted unique UTC dates (YYYY-MM-DD) taken from the results files' own
    ``environment.timestamp_utc``; empty when no file carries a parsable
    timestamp (the footnote then says the date is unrecorded).

    >>> _measurement_dates([{"environment": {"timestamp_utc": "2026-07-10T01:01:33+00:00"}}])
    ['2026-07-10']
    >>> _measurement_dates([{"environment": {"timestamp_utc": None}}, {"environment": {}}])
    []
    """
    dates = set()
    for result in results:
        stamp = result.get("environment", {}).get("timestamp_utc")
        if isinstance(stamp, str) and re.match(r"^\d{4}-\d{2}-\d{2}T", stamp):
            dates.add(stamp[:10])
    return sorted(dates)


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def engine_row_label(result: dict) -> str:
    """Human-facing table row label for one result.

    The two vLLM baseline arms must be tellable apart at a glance, so a vLLM
    result is labeled from its own recorded ``engine_config.vllm_version``
    ("vllm 0.9.2" / "vllm 0.24.0") - the version the measuring venv actually
    had installed, never the file or registry name. Everything else (and a
    vLLM result whose version capture failed) falls back to the registry
    engine name.

    >>> engine_row_label({"engine": "vllm", "engine_config": {"vllm_version": "0.9.2"}})
    'vllm 0.9.2'
    >>> engine_row_label({"engine": "vllm024", "engine_config": {"vllm_version": "0.24.0"}})
    'vllm 0.24.0'
    >>> engine_row_label({"engine": "vllm024", "engine_config": {"vllm_version": None}})
    'vllm024'
    >>> engine_row_label({"engine": "redline", "engine_config": {"module_version": "0.1.0"}})
    'redline'
    """
    engine = result["engine"]
    version = result.get("engine_config", {}).get("vllm_version")
    if engine.startswith("vllm") and version:
        return f"vllm {version}"
    return engine


def _label_collision(results_by_engine: dict, result: dict) -> dict | None:
    """The already-collected result (different engine name) whose row label
    would collide with ``result``'s, or None. Two arms rendering the same
    label (e.g. an engine="vllm" file measured under the 0.24 venv next to
    the formal vllm024 arm) would make the table ambiguous about what was
    measured - refused, never disambiguated silently."""
    label = engine_row_label(result)
    for other in results_by_engine.values():
        if other["engine"] != result["engine"] and engine_row_label(other) == label:
            return other
    return None


def format_cell(entry: dict, metric: str, flagged: bool) -> str:
    """One table cell: median with min-max, dispersion-flagged with a dagger.

    >>> format_cell({"value": 0.512, "min": 0.5, "max": 0.52}, "ttft_p50_s", False)
    '512.0 (500.0-520.0)'
    >>> format_cell({"value": 3210.5, "min": 3190.0, "max": 3290.2}, "throughput_tok_s", True)
    '3210.5 (3190.0-3290.2) †'
    """
    scale = 1000.0 if metric in _MS_METRICS else 1.0
    text = (
        f"{entry['value'] * scale:.1f} "
        f"({entry['min'] * scale:.1f}-{entry['max'] * scale:.1f})"
    )
    return f"{text} †" if flagged else text


def _sort_key(sequence: tuple, value: str) -> tuple:
    return (sequence.index(value) if value in sequence else len(sequence), value)


def _reproduction_lines(results: list[dict]) -> list[str]:
    """The reproduction section: harness prerequisites (pointers only - the
    pinned versions, hashes, and launch lines live in bench/FAIRNESS.md) plus
    the exact recorded command line of every rendered run, verbatim from its
    results file's ``environment.command_line``. Commands are static text or
    sourced from the results files; no measured value is written here."""
    recorded = {
        (result["case"], result["engine"]): " ".join(
            str(part) for part in result["environment"]["command_line"]
        )
        for result in results
    }
    ordered = sorted(
        recorded,
        key=lambda key: (_sort_key(CASE_ORDER, key[0]), _sort_key(ENGINE_ORDER, key[1])),
    )
    return [
        "### Reproducing these numbers",
        "",
        "1. Build the engine (presets in `CMakePresets.json`): "
        "`cmake --preset pod-release && cmake --build --preset pod-release`, "
        "then `ctest --preset pod-release`.",
        "2. Fetch the pinned model checkpoint: `python scripts/fetch_model.py` "
        "(revision pin documented in `docs/MODEL_SPEC.md`).",
        "3. Set up the baselines exactly as pinned in `bench/FAIRNESS.md` "
        '("Engine configuration"): each vLLM arm from its own freeze file in '
        "its own virtual environment (`bench/requirements.lock` for the "
        "`vllm` rows, `bench/requirements-vllm024.lock` for the `vllm024` "
        "rows); llama.cpp built at the recorded commit, the FP16 GGUF "
        "conversion with its recorded hash, and the recorded `llama-server` "
        "launch line (per-case context sizing in the same file).",
        "4. Verify the cross-language workload identity, then run the "
        "output-equivalence gate before measuring anything:",
        "",
        "   ```",
        "   python -m bench.workload --selftest   # must equal: redline_bench --selftest-workload",
        "   python -m bench.run_bench --equivalence-gate --engines redline,vllm,llamacpp \\",
        "       --model-dir <model_dir> --out bench/results/equivalence/transcript.json",
        "   ```",
        "",
        "5. The recorded argv of every run in the tables above, verbatim from "
        "its results file (`environment.command_line`). Paths are the benchmark "
        "machine's; `PYTHONPATH` carries the built `redline` module, each vLLM "
        "arm's rows run under that arm's pinned virtual environment's "
        "interpreter, and the llamacpp rows require the running `llama-server` "
        "from step 3:",
        "",
        "   ```",
        *(f"   {recorded[key]}" for key in ordered),
        "   ```",
        "",
        "6. Regenerate this README section from the committed results: "
        "`python -m bench.report --results bench/results/raw/ --write-readme README.md`.",
    ]


def render_markdown(results: list[dict]) -> str:
    """Results -> markdown block (tables per case + scope caption + environment
    footnote). Raises ReportError on duplicate engine/case pairs or mixed
    environments."""
    if not results:
        raise ReportError("nothing to render")
    gpu, driver = check_same_environment(results)

    by_case: dict = {}
    for result in results:
        engines = by_case.setdefault(result["case"], {})
        if result["engine"] in engines:
            raise ReportError(
                f"duplicate results for engine={result['engine']} case={result['case']} "
                f"({engines[result['engine']]['_source']} and {result['_source']})"
            )
        clash = _label_collision(engines, result)
        if clash is not None:
            raise ReportError(
                f"ambiguous row label {engine_row_label(result)!r} for "
                f"case={result['case']}: engines {clash['engine']} "
                f"({clash['_source']}) and {result['engine']} ({result['_source']}) "
                "would render identically"
            )
        engines[result["engine"]] = result

    lines: list[str] = ["## Benchmark results", ""]
    for case in sorted(by_case, key=lambda c: _sort_key(CASE_ORDER, c)):
        engines = by_case[case]
        sample = next(iter(engines.values()))
        w = sample["workload"]
        plural = "request" if w["num_requests"] == 1 else "requests"
        lines.append(
            f"### case `{case}` - {w['num_requests']} {plural}, "
            f"{w['input_len']} in / {w['output_len']} out"
        )
        lines.append("")
        headers = ["engine"] + [header for _, header in COLUMNS]
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("|" + "|".join(["---"] * len(headers)) + "|")
        for engine in sorted(engines, key=lambda e: _sort_key(ENGINE_ORDER, e)):
            result = engines[engine]
            flagged = bool(result["dispersion"].get("flag"))
            row = [f"`{engine_row_label(result)}`"]
            for metric, _ in COLUMNS:
                entry = result["metrics"].get(metric)
                if entry is None:
                    row.append("-")
                else:
                    row.append(format_cell(entry, metric, flagged and metric == HEADLINE_METRIC))
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    lines.append(f"_{SCOPE_CAPTION}_")
    lines.append("")
    if gpu is not None:
        env_note = f"Environment: {gpu}, driver {driver or 'unrecorded'}"
    else:
        env_note = "Environment: GPU capture unavailable in these results files"
    dates = _measurement_dates(results)
    if not dates:
        measured = "measurement date unrecorded"
    elif len(dates) == 1:
        measured = f"measured {dates[0]} (UTC)"
    else:
        measured = f"measured {dates[0]} to {dates[-1]} (UTC)"
    pins = "; ".join(
        _engine_versions(
            sorted(results, key=lambda r: _sort_key(ENGINE_ORDER, r["engine"]))
        )
    )
    lines.append(
        f"_{env_note}; {measured}. Engines: {pins}. Full environment capture "
        "(clocks, versions, pip freeze, exact command line) in each results JSON._"
    )
    lines.append("")
    lines.extend(_reproduction_lines(results))
    lines.append("")
    return "\n".join(lines)


def splice_readme(readme_path: str, block: str) -> None:
    """Replace the generated block between the README markers; error when the
    markers are absent (they are added deliberately, never injected)."""
    path = Path(readme_path)
    text = path.read_text(encoding="utf-8")
    if README_BEGIN not in text or README_END not in text:
        raise ReportError(
            f"{readme_path}: missing generated-results markers; add\n"
            f"{README_BEGIN}\n{README_END}\nwhere the table belongs"
        )
    head, _, rest = text.partition(README_BEGIN)
    _, _, tail = rest.partition(README_END)
    path.write_text(
        head + README_BEGIN + "\n" + block.rstrip() + "\n" + README_END + tail,
        encoding="utf-8",
        newline="\n",  # byte-identical output on every platform
    )


# --------------------------------------------------------------------------
# --check: schema + duplicate + dispersion-flag audit (the results gate)
# --------------------------------------------------------------------------


def check_results(paths: list[str]) -> int:
    """Audit raw results: every file must validate - including the raw-data
    audit that recomputes forced lengths and every metric from the committed
    per-token data (``_audit_raw_data``) - and duplicate engine/case pairs,
    ambiguous row labels, dispersion flags and environment consistency are
    reported. Duplicate pairs and label collisions are failures because
    ``render_markdown`` refuses them - a directory that passes ``--check``
    must also render. The vLLM arms are distinct engines here: (vllm, case)
    and (vllm024, case) may coexist; two files of the SAME engine/case never
    may. Returns a process exit code."""
    failures = 0
    results = []
    seen_pairs: dict[tuple, str] = {}
    seen_labels: dict[tuple, tuple] = {}
    for path in _iter_result_files(paths):
        try:
            result = json.loads(path.read_text(encoding="utf-8"))
            validate_result(result, str(path))
        except (OSError, json.JSONDecodeError, ReportError) as error:
            failures += 1
            print(f"FAIL {path}: {error}")
            continue
        result["_source"] = str(path)
        pair = (result["engine"], result["case"])
        if pair in seen_pairs:
            failures += 1
            print(
                f"FAIL {path}: duplicate results for engine={pair[0]} "
                f"case={pair[1]} (already provided by {seen_pairs[pair]}); "
                "this directory would not render"
            )
            continue
        label = engine_row_label(result)
        prior = seen_labels.get((result["case"], label))
        if prior is not None and prior[0] != result["engine"]:
            failures += 1
            print(
                f"FAIL {path}: ambiguous row label {label!r} for "
                f"case={result['case']} (engine={result['engine']} here, "
                f"engine={prior[0]} in {prior[1]}); this directory would "
                "not render"
            )
            continue
        seen_pairs[pair] = str(path)
        seen_labels[(result["case"], label)] = (result["engine"], str(path))
        results.append(result)
        dispersion = result["dispersion"]
        flag = " DISPERSION-FLAGGED" if dispersion.get("flag") else ""
        rerun = " (re-ran once)" if dispersion.get("reran") else ""
        print(
            f"ok   {path}: engine={result['engine']} case={result['case']} "
            f"trials={len(result['trials'])}{rerun}{flag}"
        )
    if results:
        try:
            check_same_environment(results)
        except ReportError as error:
            failures += 1
            print(f"FAIL environment consistency: {error}")
    flagged = sum(1 for r in results if r["dispersion"].get("flag"))
    print(
        f"[report] checked {len(results)} valid file(s), {failures} failure(s), "
        f"{flagged} dispersion-flagged"
    )
    return 1 if failures else 0


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m bench.report",
        description="Render committed benchmark results JSON into markdown "
        "(no number appears anywhere that is not generated from a results file).",
    )
    parser.add_argument(
        "--results",
        nargs="+",
        metavar="PATH",
        help="result JSON files and/or directories to render",
    )
    parser.add_argument("--out", help="write the markdown here instead of stdout")
    parser.add_argument(
        "--write-readme",
        metavar="README",
        help="splice the table between the BENCH_RESULTS markers of this file",
    )
    parser.add_argument(
        "--check",
        nargs="+",
        metavar="PATH",
        help="audit results files/directories and exit non-zero on "
        "violations: schema; forced lengths and all metrics recomputed from "
        "the committed per-token data (a truncated token list or an edited "
        "median fails even with green self-reported flags); summary/median/"
        "dispersion re-derivation; duplicate engine/case pairs; ambiguous "
        "row labels; environment consistency",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    if args.check and (args.results or args.out or args.write_readme):
        raise SystemExit("--check runs alone")
    if args.check:
        return check_results(args.check)
    if not args.results:
        raise SystemExit("pass --results PATH... (or --check PATH...)")

    results = load_results(args.results)
    block = render_markdown(results)
    if args.write_readme:
        splice_readme(args.write_readme, block)
        print(f"[report] wrote results table into {args.write_readme}")
    if args.out:
        Path(args.out).write_text(block, encoding="utf-8")
        print(f"[report] wrote {args.out}")
    elif not args.write_readme:
        print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
